services:
  react-api-sumple:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-api-sumple
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev -- --host